### ISSUE TITLE
DOI for exports ?

### ISSUE THREAD

**Issue by mathieuLU** [Lund-University-Biodiversity-data/datahost-api-client#13]

**Comment by anneliejonsson** [comment]
I've read the contract as well as the technical appendix and there is no mention of creating DOIs (or something similar) for downloaded files.

However, for the annual report they ask for the following:
number of database searches
number of downloaded files

**Comment by mathieuLU** [comment]
good to hear. 
But it means that I should store somewhere these statistics ?

**Comment by anneliejonsson** [comment]
Yes, I guess it would be good to have let's say the totals per month stored somewhere.

I think the number of downloads is the critical number. I'm not sure that they thought things through properly when they wrote that we should report number of searches. I mean, I'm not sure how useful that information is to them. But we should post the question in the API-group and let Tommy/Hanna take it further up in NV to make sure we don't add a feature that is  worthless.
